- name: install kepler theme
  command: wp theme install --allow-root https://storage.googleapis.com/kepler-download/kepler-theme.zip?ignoreCache=1 --activate
  args:
    chdir: "/var/www/{{ _domain }}/public_html"
    executable: /usr/local/bin/wp

- name: activate kepler plugin
  command: wp plugin install --allow-root https://storage.googleapis.com/kepler-download/kepler-builder.zip --activate
  args:
    chdir: "/var/www/{{ _domain }}/public_html"
    executable: /usr/local/bin/wp

- name: updating document root ownership
  file:
    path: "/var/www/{{ _domain }}/public_html"
    state: directory
    recurse: yes
    owner: www-data
    group: www-data