# linode ansible playbook

- name: configuring MainConcept FFmpeg plugins
  hosts: localhost
  connection: local
  gather_facts: true
  any_errors_fatal: true
  user: root
  vars_files:
    - group_vars/linode/vars
  roles:
    - common
    - mcffmpeg
    - post
